In [1122]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.metrics import confusion_matrix

In [1123]:
#1)

#a)
data = pd.read_csv(r'C:\Users\Radu\Desktop\facultate\Anul3\Calcul Numeric\Lab4\iris.data')
data = np.array(data)

#shuffle pe data ca sa fie in mod aleator
np.random.shuffle(data)

#set de antrenament cu 100 de semnale
train = data[:100, :]
test = data[100:, :]

#set de test cu 50 de semnale
train_features = train[:, 0:4]
train_labels = train[:, 4]

test_features = test[:, 0:4]
test_labels = test[:, 4]


In [1124]:
#b) antrenarea algoritmului

clf = svm.SVC(kernel='linear')
clf.fit(train_features, train_labels)




SVC(kernel='linear')

In [1125]:
#c) testarea algoritmului pe setul test, eroare de clasificare si matricea de confuzie
nr = 0
predictii = clf.predict(test_features)
for i in range(0, test_labels.shape[0]):
    if(test_labels[i] != predictii[i]):
        nr += 1
# print(test_labels[:10])
nr_rezultate_corecte = 50 - nr
print(f'{(nr_rezultate_corecte / 50) * 100}% rezultate corecte ')



#matricea de confuzie

print(confusion_matrix(test_labels, predictii))

96.0% rezultate corecte 
[[12  0  0]
 [ 0 17  2]
 [ 0  0 18]]


In [1126]:
#d) aceeasi chestie doar ca utilizand kernel de tip RBF
nr = 0
clf_rbf = svm.SVC(kernel='rbf')
clf_rbf.fit(train_features, train_labels)
predictii = clf_rbf.predict(test_features)
for i in range(0, test_labels.shape[0]):
    if(test_labels[i] != predictii[i]):
        nr += 1
nr_rezultate_corecte = 50 - nr
print(f'{(nr_rezultate_corecte / 50) * 100}% rezultate corecte ')

print(confusion_matrix(test_labels, predictii))

94.0% rezultate corecte 
[[12  0  0]
 [ 0 18  1]
 [ 0  2 16]]
